name: Instagram Data Cron Job

on:
  # Schedule: Run the job every day at midnight (UTC)
  schedule:
    - cron: '0 0 * * *'

  # Manual trigger: Adds a "Run Workflow" button in the GitHub Actions UI
  workflow_dispatch:

jobs:
  fetch-instagram-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Use the appropriate Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the cron job script
      - name: Run cron job
        run: npm run cron-job
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
